### ISSUE TITLE
Trouble with Webpack + Fuse

### ISSUE THREAD

**Issue by colebemis** [krisk/Fuse#180]
I'm having trouble using Fuse.js with Webpack. Here are the steps to reproduce the issue I'm having:

```
webpack v3.4.1
fuse.js v3.0.5
```

### Step 1: Add fuse.js
```
$ yarn add fuse.js
```

### Step 2: Import Fuse
```javascript
import Fuse from 'fuse.js';
```

### Step 3: Run webpack
```
$ yarn webpack
```

### Results

```
yarn webpack v0.27.5
$ "/Volumes/Mozart/Users/colebemis/Documents/tabio/node_modules/.bin/webpack"
Hash: 68dbc826db982454846a
Version: webpack 3.4.1
Time: 10563ms
        Asset       Size  Chunks                    Chunk Names
    bundle.js     914 kB       0  [emitted]  [big]  main
bundle.js.map    1.51 MB       0  [emitted]         main
manifest.json  157 bytes          [emitted]
   popup.html  503 bytes          [emitted]
  [91] ./src/index.jsx 4.76 kB {0} [built]
    + 216 hidden modules

ERROR in ./node_modules/fuse.js/dist/fuse.js
Module build failed: ReferenceError: Unknown plugin "babel-plugin-add-module-exports" specified in "/Volumes/Mozart/Users/colebemis/Documents/tabio/node_modules/fuse.js/.babelrc" at 0, attempted to resolve relative to "/Volumes/Mozart/Users/colebemis/Documents/tabio/node_modules/fuse.js"
    at /Volumes/Mozart/Users/colebemis/Documents/tabio/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Volumes/Mozart/Users/colebemis/Documents/tabio/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Volumes/Mozart/Users/colebemis/Documents/tabio/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Volumes/Mozart/Users/colebemis/Documents/tabio/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Volumes/Mozart/Users/colebemis/Documents/tabio/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Volumes/Mozart/Users/colebemis/Documents/tabio/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Volumes/Mozart/Users/colebemis/Documents/tabio/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Volumes/Mozart/Users/colebemis/Documents/tabio/node_modules/babel-loader/lib/index.js:49:20)
    at Object.module.exports (/Volumes/Mozart/Users/colebemis/Documents/tabio/node_modules/babel-loader/lib/index.js:174:20)
 @ ./src/index.jsx 12:0-27
error Command failed with exit code 2.
```

I've used Fuse in the past and this is the first time I've had any problems. I'd really help appreciate some help resolving this issue. Thanks!

**Comment by JeffreyHyer** [comment]
@colebemis I've run into similar issues in the past with this and other libraries. Usually `yarn add babel-plugin-add-module-exports` (or replace with the name of any other "Unknown plugin" it complains about) fixes the issue.

**Comment by colebemis** [comment]
@JeffreyHyer Thanks! I tried that. The problem is it just kept asking for more dependencies. After I installed three extra dependencies and there was still a new error I figured that there must be a better fix. One of the things I liked about Fuse is that it has zero dependencies and just worked out of the box.

**Comment by JeffreyHyer** [comment]
@colebemis Yeah I understand that, it gets pretty annoying.

**Comment by Leeds-eBooks** [comment]
This is blocking me too, really glad to find this issue and know it's not just me! Have you made any progress debugging it?

**Comment by Leeds-eBooks** [comment]
In my case, I'm using react native which uses a different packager than Webpack, which makes me think it's actually a babel issue.

**Comment by colebemis** [comment]
I fixed this issue by ignoring `node_modules` in my webpack config.
```javascript
module.exports = {
  ...
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        loader: 'babel-loader',
        exclude: /node_modules/, // <-- this fixed the error
      },
    ],
  },
}
```

**Comment by zivchen** [comment]
Doesnt work for me on React Native
"fuse.js": "^3.2.0"

Thats the error:
error: bundling failed: Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at Object.readSync (/Users/zivchen/Documents/Business/edocate/edocate-app-snowflake/node_modules/graceful-fs/polyfills.js:138:28)
