### ISSUE TITLE
ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-fuse/src/VueFuse.vue

### ISSUE THREAD

**Issue by hitolv4** [krisk/Fuse#187]
hi there i'm trying to use this package but y get this error 

ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-fuse/src/VueFuse.vue
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "/home/hitokiri/g_empleo/front/node_modules/vue-fuse/.babelrc" at 0, attempted to resolve relative to "/home/hitokiri/g_empleo/front/node_modules/vue-fuse"
    at /home/hitokiri/g_empleo/front/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/home/hitokiri/g_empleo/front/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/home/hitokiri/g_empleo/front/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/home/hitokiri/g_empleo/front/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/hitokiri/g_empleo/front/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/hitokiri/g_empleo/front/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/hitokiri/g_empleo/front/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/hitokiri/g_empleo/front/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/home/hitokiri/g_empleo/front/node_modules/babel-loader/lib/index.js:163:20)
 @ ./~/vue-fuse/src/VueFuse.vue 4:2-91
 @ ./~/vue-fuse/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

is the fist time this append to me,
ty for this  package keep up your work

**Comment by narkissbv** [comment]
Have you managed to solve this? Just got a similar problem with my project...

**Comment by clarkcalina** [comment]
same problem..

**Comment by majiali** [comment]
same problem

**Comment by SumanBandopadhyay** [comment]
Same issue here. I am facing this issue when trying to use 'vue-windows'
