### ISSUE TITLE
TypeError: Cannot read property 'location' of undefined

### ISSUE THREAD

**Issue by Olian04** [krisk/Fuse#210]
Getting a TypeError when trying to use Fuse with node 9.2.0
```
/home/olian04/Documents/Projects/xs/node_modules/fuse.js/dist/fuse.js:557
    var _ref$location = _ref.location,
                             ^

TypeError: Cannot read property 'location' of undefined
    at new Fuse (/home/olian04/Documents/Projects/xs/node_modules/fuse.js/dist/fuse.js:557:30)
    at querySegments.reduce (/home/olian04/Documents/Projects/xs/app/index.js:10:24)
    at Array.reduce (<anonymous>)
    at xs (/home/olian04/Documents/Projects/xs/app/index.js:9:32)
    at Object.<anonymous> (/home/olian04/Documents/Projects/xs/demo/test.js:3:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

Fuse is the only package installed, and this fails: 
```js
const Fuse = require('fuse.js');
new Fuse([]); // Fails here!
```

**Versions:**
Fuse: 3.2.0
Node: 9.2.0
Npm: 5.5.1
Ubuntu: 17.04

**Comment by curtgrimes** [comment]
I encountered the same issue. Pass in an empty options object.
```js
new Fuse([], {});
```

**Comment by jhbell** [comment]
We had a similar issue trying to use Fuse.js with a React project. Our problem was that we were passing in the options from a react component's state. 
```javascript
var fuse = new Fuse(data, this.state.options);
```
We sloved the problem by directly putting our options object into the constructor for Fuse(). I.e.
```javascript
var fuse = new Fuse(data, {keys: ['title', 'description'], id: 'id'});
```

**Comment by AlexVFornazieri** [comment]
Hey guys, i have same issue here, but my array not is empty, any one have a solution?
